# Generated by Django 2.2.7 on 2020-09-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200916_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact Number')),
                ('informed_on', models.DateField(auto_now_add=True, verbose_name='Informed On')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Language Preferred'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(default=0, verbose_name='zip Code'),
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField(verbose_name='Schedule Date')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Language Preferred')),
                ('area', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip', models.IntegerField(default=0, verbose_name='Zip Code')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100, verbose_name='Donor Name')),
                ('donation_date', models.DateField(verbose_name='Donation date')),
                ('donation_item', models.CharField(blank=True, max_length=100, verbose_name='Donation Item')),
                ('donation_amount', models.CharField(blank=True, max_length=100, verbose_name='Donation Amount')),
                ('donated_to', models.CharField(blank=True, max_length=100, verbose_name='Donated To')),
                ('donated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Page')),
            ],
        ),
    ]
